"""Deterministic stable ID generation for V0 domain entities.

Rules (see AGENTS.md "AI Rules" and DATA_MODEL #13):

- IDs are generated by code, never by an LLM.
- Same deterministic input produces the same ID.
- IDs never depend on database row order.
- Missing/empty meaningful input is rejected instead of inventing an
  identifier.

DATA_MODEL #13 *suggests* human-readable sequential IDs such as
``DOC-HKEX-2025-001`` or ``TOPIC-0001``. Sequential numbering requires
persistent allocation state and would otherwise depend on registration
order, so P1 (which has no persistence) derives the suffix from a
SHA-256 digest of the meaningful inputs while keeping the suggested
prefixes. ``FW-`` IDs remain fully human-readable.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Sequence

FRAMEWORK_PREFIX = "FW-"
DOCUMENT_PREFIX = "DOC-"
CLAUSE_PREFIX = "CL-"
TOPIC_PREFIX = "TOPIC-"
MAPPING_PREFIX = "MAP-"

_DIGEST_LENGTH = 12


def _digest(parts: Sequence[str], length: int = _DIGEST_LENGTH) -> str:
    """Canonical SHA-256 digest over an ordered list of string parts."""
    payload = json.dumps(list(parts), ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:length]


def _require_parts(parts: dict[str, str | None]) -> list[str]:
    """Validate that all required meaningful inputs are present."""
    cleaned: list[str] = []
    for name, value in parts.items():
        if value is None or not value.strip():
            raise ValueError(
                f"cannot generate a stable ID: {name!r} is missing or empty"
            )
        cleaned.append(value.strip())
    return cleaned


def generate_framework_id(code: str) -> str:
    """Framework IDs are human-readable: ``FW-<CODE>`` (e.g. FW-HKEX)."""
    if code is None or not code.strip():
        raise ValueError("cannot generate a framework ID from an empty code")
    return f"{FRAMEWORK_PREFIX}{code.strip().upper()}"


def generate_document_id(framework_id: str, title: str, version: str) -> str:
    """Stable ID for one identifiable version of one source document."""
    parts = _require_parts(
        {"framework_id": framework_id, "title": title, "version": version}
    )
    return f"{DOCUMENT_PREFIX}{_digest(parts)}"


def generate_clause_id(
    document_id: str,
    source_item_type: str,
    original_text: str,
    clause_number: str | None = None,
    source_code: str | None = None,
    heading: str | None = None,
) -> str:
    """Stable ID for an atomic source unit (SourceClause).

    The digest covers the document, the unit type, whichever source
    identifiers the family supports, and the original text, so the same
    extracted unit always yields the same ID.
    """
    parts = _require_parts(
        {
            "document_id": document_id,
            "source_item_type": source_item_type,
            "original_text": original_text,
        }
    )
    parts.extend(
        [
            (clause_number or "").strip(),
            (source_code or "").strip(),
            (heading or "").strip(),
        ]
    )
    return f"{CLAUSE_PREFIX}{_digest(parts)}"


def generate_topic_id(name: str, parent_topic_id: str | None = None) -> str:
    """Stable ID for a topic; the parent participates so that the same
    name under different parents does not collide."""
    parts = _require_parts({"name": name})
    parts.append((parent_topic_id or "").strip())
    return f"{TOPIC_PREFIX}{_digest(parts)}"


def generate_mapping_id(topic_id: str, clause_id: str) -> str:
    """Stable ID for a topic-to-source-unit mapping."""
    parts = _require_parts({"topic_id": topic_id, "clause_id": clause_id})
    return f"{MAPPING_PREFIX}{_digest(parts)}"
