"""Topic domain model (DATA_MODEL #6).

For V0, topics are imported from the pilot project rather than
generated by AI. The ``Project`` entity is intentionally deferred, so
Topic carries no ``project_id`` and no ``level_1_name`` /
``level_2_name`` persistence fields. Hierarchy is expressed through
``parent_topic_id`` + ``level``; hierarchy persistence and recursive
traversal are not part of P1.
"""

from datetime import datetime, timezone

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from .enums import TopicStatus
from .ids import TOPIC_PREFIX


class Topic(BaseModel):
    """A client or project ESG topic."""

    model_config = ConfigDict(validate_assignment=True)

    topic_id: str = Field(min_length=1)
    name: str = Field(min_length=1)
    parent_topic_id: str | None = None
    description: str | None = None
    level: int | None = Field(default=None, ge=1)
    status: TopicStatus = TopicStatus.ACTIVE
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("topic_id", "parent_topic_id")
    @classmethod
    def _topic_id_shape(cls, value: str | None) -> str | None:
        if value is not None and not value.startswith(TOPIC_PREFIX):
            raise ValueError(f"topic ids must start with {TOPIC_PREFIX!r}")
        return value

    @model_validator(mode="after")
    def _hierarchy_sanity(self) -> "Topic":
        # Sanity checks that are possible without persistence.
        if self.parent_topic_id is not None:
            if self.parent_topic_id == self.topic_id:
                raise ValueError("a topic cannot be its own parent")
            if self.level is not None and self.level < 2:
                raise ValueError("a child topic must have level >= 2")
        else:
            if self.level is not None and self.level != 1:
                raise ValueError("a root topic (no parent) must have level 1")
        return self
